# Welcome to Jekyll!
#

# Site settings
title: vinodh.org
description: <>
owner: Your Name # or company name
#first_published: 2016 # if migrating another site, the year of your first publish
email: info@vinodh.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vinodh98.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/thisvinodh
  github: https://github.com/vinodh98
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
